name: Deploy to production

on:
    push:
        branches:
            - "production"

jobs:
    redeploy_everything:
        name: Deploying everything to production cluster
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH Key
              run: |
                echo "${{ secrets.AWS_PEM_KEY }}" &> ~/ssh_key
                chmod 600 ~/ssh_key

            - name: Add server to known hosts
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H 51.20.8.137 >> ~/.ssh/known_hosts

            - name: SSH and deploy
              run: |
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@51.20.8.137 "
                    export NVM_DIR=\$HOME/.nvm
                    source \$NVM_DIR/nvm.sh
                    cd devops-practice
                    git pull origin production
                    pnpm install
                    pnpm run build
                    pm2 restart fe-server
                    pm2 restart http-server
                    pm2 restart ws-server
                "    