name: Deploy to staging

on:
    push:
        branches:
            - "main"

jobs:
    redeploy_everything:
        name: Deploying everything to the staging cluster
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH Key
              run: |
                echo "${{ secrets.AWS_PEM_KEY }}" &> ~/ssh_key
                chmod 600 ~/ssh_key

            - name: Add server to known_hosts
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H 16.171.169.26 >> ~/.ssh/known_hosts    

            - name: SSH and deploy
              run: |
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@16.171.169.26 "
                    export NVM_DIR=\$HOME/.nvm
                    source \$NVM_DIR/nvm.sh
                    cd devops-practice
                    git pull
                    pnpm install
                    pnpm run build
                    pm2 restart fe-server
                    pm2 restart http-server
                    pm2 restart ws-server
                "